server:
  port: 80

spring:
  datasource:
    druid:
      url: jdbc:mysql://119.91.78.112:3306/test_db?useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
